### PR TITLE
upgrade omero_install to the latest 5.3.0-m7 tag

### PR DESCRIPTION
**Pull request by atarkowska**
upgrade omero_install to the latest 5.3.0-m7 tag 

Ideally if in the future that could happen automatically somehow

cc @jburel

### CODE REVIEW

**Comment by atarkowska** [comment]
could this be tagged and released to https://hub.docker.com/r/openmicroscopy/devslave-c7/

**Comment by joshmoore** [comment]
@aleksandra-tarkowska : do you want to list this in standup when you're ready?

**Comment by atarkowska** [comment]
This PR is waiting on https://github.com/ome/omero-install/pull/129, likely `5.3.0-RC1` ?

**Comment by atarkowska** [comment]
Are we going to divert branches or we will release 0.1.x for 5.2 and 0.2.x for 5.3. Basically if we are going still releasing 5.2 I think we should have base image for both.

**Comment by joshmoore** [comment]
I think another 5.2 release is unlikely, but if we need to we can always branch off `dev_0_1` or whatever after the fact.

**Comment by atarkowska** [comment]
Sure, but at the moment we need 5.2 and 5.3 devspaces

**Comment by atarkowska** [comment]
Once we are ready with omero-install tag https://github.com/ome/omero-install/pull/129#issuecomment-271414976 this can be released

**Comment by sbesson** [comment]
As discussed today I propose to tag this as 0.3.0 as it operates the switch from 5.2.5 to 5.3.0

**Comment by joshmoore** [comment]
Pushed `0.3.0`

**Pull request merged**
