### PR TITLE
Bump to latest release version

### PR DESCRIPTION
**Pull request by jburel**
Bump to latest release version

Probably something to add to the release board

### CODE REVIEW

**Comment by joshmoore** [comment]
`E: Package 'docker-engine' has no installation candidate`

**Comment by jburel** [comment]
restarted travis but oracle17/18 failed last night
I will be of the opinion to exclude them from the check for now so we can move forward
since this is blocking us for devspace (locale issue) => secvul 
cc @sbesson

**Comment by sbesson** [comment]
Discussed this morning, no veto to temporarily disabling Oracle in Travis as JDK7/8 are tested via OpenJDK and the devslave-c7 based images are currently broken wrt locales. Can you update `.travis.yml` and create a related issue?

**Comment by jburel** [comment]
issue https://github.com/openmicroscopy/devslave-c7-docker/issues/14

**Pull request merged**
