### PR TITLE
Bump omero-install to 5.5.0-m3

### PR DESCRIPTION
**Pull request by joshmoore**
cc: @jburel Hopefully this will allow devspace PRs to turn green.

### CODE REVIEW

**Comment by joshmoore** [comment]
travis is unfortunately happy -- https://travis-ci.org/openmicroscopy/devslave-c7-docker/builds/526873074

Looks like `while ! docker logs jenkins 2>&1 | grep "from: /${SLAVE_ADDR}"` is no longer detecting anything. Perhaps the outputs have changed?

**Comment by joshmoore** [comment]
Ah...

```
[jamoore@idr1-slot2 devslave-c7-docker]$ docker logs devslave
Running java -jar /tmp/swarm-client-3.14.jar -fsroot /root -master http://172.17.0.3:50000 -executors 1 -labels slave
/tmp/jenkins-slave.sh: line 41: exec: java: not found
```

**Comment by joshmoore** [comment]
@jburel : looks like the JAVAVER variable has diverged: openjdk18 vs. openjdk1.8. We should likely make omero-install fail fast if the value is unknown as opposed to not installing java. I'll push a fix to this PR.

**Comment by joshmoore** [comment]
If this is green, I propose 0.6.0 (and 5.5.0 can be 0.6.1).

**Review by sbesson — APPROVED** [review]
I assume the `JAVAVER` breaking change comes from https://github.com/ome/omero-install/pull/192/files#diff-3693e7b7a89aa5fccf8839cd96841151.

Based on the assumption that our dependencies are frozen for OMERO 5.5.0, there should be no more breaking upstream change in `omero-install` i.e. it makes sense to me to tag this as `0.6.0` and follow-up with a patch release bumping to the final 5.5.0 version of `omero-install`.

**Comment by joshmoore** [comment]
Due to Docker Hub token cancellation, tags are not autobuilding. Pushed manually.

**Comment by joshmoore** [comment]
Missed a openjdk18 in the Dockerfile. Will open a 0.6.1. (I'm pushing the docker image _first_ so I can be sure it works)

**Pull request merged**
